server:
  port: 8082

spring:
  application:
    name: cart-service
  redis:
    host: redis-db
    port: 6379
  main:
    allow-bean-definition-overriding: true
  # ?? Configuration pour la base de données
  datasource:
    url: jdbc:postgresql://postgres-db:5432/ecommerce
    username: postgres
    password: ModienneG
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

product-service:
  url: http://product-service
