server:
  port: 8082

spring:
  application:
    name: cart-service
  redis:
    host: redis-db
    port: 6379
  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

product-service:
  url: http://product-service
