spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://postgres-db:5432/ecommerce
    username: postgres
    password: ModienneG
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # Met à jour le schéma de la BDD.
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
server:
  port: 8080